// export const ADD_ADMIN_USER_SUCCESS = 'ADD_ADMIN_USER_SUCCESS';
// export const ADD_ADMIN_USER_FAILURE = 'ADD_ADMIN_USER_FAILURE';

// export const GET_ADMIN_USERS_SUCCESS = 'GET_ADMIN_USERS_SUCCESS';
// export const GET_ADMIN_USERS_FAILURE = 'GET_ADMIN_USERS_FAILURE';

// export const SET_USER_DATA = 'SET_USER_DATA';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
//export const SEARCH_PRODUCTS_FAILURE = 'SEARCH_PRODUCTS_FAILURE';

